#!/bin/zsh


file=$(echo "$1" | sed -E 's/.*file=([^&]+).*/\1/');
line=$(echo "$1" | sed -E 's/.*line=([^&]+).*/\1/');

pidof clion;

if [[ $? -ne 0 ]]; then
	notify-send --app-name="clion:// handler" --icon="open-link" "CLion is not running, opening with default app"
	xdg-open "$file";
	exit;
fi

if [[ -z "file" ]]; then
	exit;
fi

if [[ "$line" == "$1" ]]; then
	line="1";
fi

$HOME/.local/binaries/clion/bin/clion --line "$line" "$file"
